[version]
current = "0.2.27"

regex = '''
\d+\.\d+\.\d+(-(.*))?
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "charts/ballroom/Chart.yaml"
[[file]]
src = "charts/ballroom/templates/statefulset.yaml"
