{{ if and .Values.ingress.enabled .Values.ingress.vanilla.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  rules:
    {{- range $i, $e := until (.Values.pod.replicas | int) }}
    - host: {{ $.Values.ingress.host.instancePrefix }}{{ add $i 1 }}-{{ $.Values.ingress.host.sessionID }}.{{ $.Values.ingress.host.domain }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $.Release.Name }}-{{ $i }}
              port:
                number: 80
    {{- end }}  
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
  {{ end }}
  {{ end }}
{{ end }}
