---
{{ if and .Values.ingress.enabled .Values.ingress.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $.Release.Name }}-gateway
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range $i, $e := until (.Values.pod.replicas | int) }}
    - {{ $.Values.ingress.host.instancePrefix }}{{ add $i 1 }}-{{ $.Values.ingress.host.sessionID }}.{{ $.Values.ingress.host.domain }}
    {{- end }}
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    {{- range $i, $e := until (.Values.pod.replicas | int) }}
    - {{ $.Values.ingress.host.instancePrefix }}{{ add $i 1 }}-{{ $.Values.ingress.host.sessionID }}.{{ $.Values.ingress.host.domain }}
    {{- end }}
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.ingress.istio.credentialName }}
{{ end }}
---
{{ if and .Values.ingress.enabled .Values.ingress.istio.enabled }}
{{- range $i, $e := until (.Values.pod.replicas | int) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Release.Name }}-vs-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.ingress.host.instancePrefix }}{{ add $i 1 }}-{{ $.Values.ingress.host.sessionID }}.{{ $.Values.ingress.host.domain }}
  gateways:
  - {{ $.Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ $.Values.service.ports.first.port }}
        host: {{ $.Release.Name }}-{{ $i }}
---
{{ end }}
{{ end }}
