---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: {{ .Values.service.ports.protocol }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      name: {{ .Values.service.ports.name }}
  clusterIP: {{ .Values.service.headless.clusterIP }}
---
{{- range $i, $e := until (.Values.pod.replicas | int) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Release.Name }}
  name: {{ $.Release.Name }}-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - protocol: {{ .Values.service.ports.protocol }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      name: {{ .Values.service.ports.name }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-{{ $i }}
  type: ClusterIP
---
{{- end }}
