apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Release.Name }}
    version: 0.2.20
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  pod.replicas: {{ .Values.pod.replicas }}
  serviceName: {{ .Release.Name }}-headless
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.registry }}:{{ .Values.image.tag }}
        name: {{ .Release.Name }}
        imagePullPolicy: Always
        {{ if .Values.configMapVolume.enabled }}
        volumeMounts:
          - name: {{ .Values.configMapVolume.name }}
            mountPath: {{ .Values.configMapVolume.mountPath }}
            readOnly: {{ .Values.configMapVolume.readOnly }}
        {{ end }}
        ports:
          - containerPort: {{ .Values.service.ports.targetPort }}
            name: {{ .Values.service.ports.name }}
        # TODO: allow user to add arbitrary amount of env values
        resources: # TODO: template and move all to values.yaml
          requests:
            cpu: {{ .Values.pod.requests.cpu }}
            memory: {{ .Values.pod.requests.memory }}
          limits:
            cpu: {{ .Values.pod.limits.cpu }}
            memory: {{ .Values.pod.limits.memory }}
      {{ if .Values.image.regcred.enabled }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-regcred
      {{ end }}
      {{ if .Values.configMapVolume.enabled }}
      volumes:
        - name: {{ .Values.configMapVolume.name }}
          configMap:
            name: {{ .Values.configMapVolume.configMapName }}
