image:
  registry: consol/debian-xfce-vnc
  tag: v2.0.1@sha256:108675d167724b9f0ecbda8464ff66c8fbe42ccd0eb5647c4f8fc8205a9c136d

ingress:
  enabled: false
  domain: "test.com"
  annotations: {}
  sessionID: "12345"
  vanilla:
    enabled: true
  istio:
    enabled: false
    credentialName: "your-secret-name-goes-here"

demo:
  players: 3
  game: sasse #TODO: drop?
  port: "8080"
