name: semantic release
on:
  push:
    branches:
      - main
jobs:
  semantic-release:
    name: Release
    runs-on: registry.gitlab.com/just-ci/images/node:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
